### ISSUE TITLE
Create data table

### ISSUE THREAD

**Issue by michaeloshea04** [michaeloshea04/ABVCalculator#3]
This app is based on a table from John Palmer's book "How To Brew".
The table is used to approximate the alcohol content of your home brew by referencing the starting gravity compared to the finishing gravity.  

1. I need to come up with a way of representing that table in some data structure.
2. I need to be able to reference that table/data structure so that I can return a value to the user based on the user inputs.

[http://howtobrew.com/book/section-1/fermenting-your-first-beer/how-much-alcohol-will-there-be](url)

There is probably a formula for this but I thought trying to reference this table would be a small challenge and easy enough to fit in a console application.

**Comment by SteveTeece** [comment]
I think a formula for this would be the best option.

Hard-coding the values from the table above could also lead to failures if something weird happens and the start or end SG is outside the normal range.

**Comment by michaeloshea04** [comment]
Logic changed to use formula instead of reference table.  
Issue closed.
